# Generated by Django 4.2.11 on 2024-04-24 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('photo', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Casting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('requirements', models.TextField()),
                ('photo', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('date_of_birth_day', models.IntegerField()),
                ('date_of_birth_month', models.IntegerField()),
                ('date_of_birth_year', models.IntegerField()),
                ('nationality', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('instagram', models.CharField(max_length=100)),
                ('facebook', models.CharField(max_length=100)),
                ('tiktok', models.CharField(max_length=100)),
                ('profession', models.CharField(max_length=200)),
                ('language_kz', models.BooleanField(default=False)),
                ('language_eng', models.BooleanField(default=False)),
                ('language_rus', models.BooleanField(default=False)),
                ('other_languages', models.CharField(blank=True, max_length=100)),
                ('skills', models.CharField(max_length=300)),
                ('about_me', models.TextField()),
                ('photo', models.ImageField(blank=True, upload_to='photos/')),
                ('video', models.FileField(blank=True, upload_to='videos/')),
                ('appearance_type', models.CharField(max_length=20)),
                ('weight', models.FloatField()),
                ('height', models.FloatField()),
                ('clothing_size', models.CharField(max_length=10)),
                ('eye_color', models.CharField(max_length=50)),
                ('hair_color', models.CharField(max_length=50)),
                ('individual_features', models.TextField()),
                ('casting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='castings', to='api.casting')),
            ],
        ),
        migrations.DeleteModel(
            name='Castings',
        ),
    ]
