# Generated by Django 4.2.11 on 2024-04-24 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_ad_casting_form_delete_castings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('requirements', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='casting',
            name='requirements',
        ),
    ]
