# Generated by Django 4.2.11 on 2024-04-24 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_position_remove_casting_requirements'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Position',
        ),
        migrations.RemoveField(
            model_name='form',
            name='casting',
        ),
        migrations.AlterField(
            model_name='casting',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='casting',
            name='name',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='casting',
            name='photo',
            field=models.TextField(blank=True),
        ),
    ]
