# Generated by Django 4.2.11 on 2024-04-24 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_delete_position_remove_form_casting_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('requirements', models.TextField()),
                ('casting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='api.casting')),
            ],
        ),
    ]
