# Generated by Django 4.2.11 on 2024-05-29 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='about_me',
        ),
        migrations.RemoveField(
            model_name='form',
            name='appearance_type',
        ),
        migrations.RemoveField(
            model_name='form',
            name='clothing_size',
        ),
        migrations.RemoveField(
            model_name='form',
            name='email',
        ),
        migrations.RemoveField(
            model_name='form',
            name='eye_color',
        ),
        migrations.RemoveField(
            model_name='form',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='form',
            name='hair_color',
        ),
        migrations.RemoveField(
            model_name='form',
            name='height',
        ),
        migrations.RemoveField(
            model_name='form',
            name='individual_features',
        ),
        migrations.RemoveField(
            model_name='form',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='form',
            name='language_eng',
        ),
        migrations.RemoveField(
            model_name='form',
            name='language_kz',
        ),
        migrations.RemoveField(
            model_name='form',
            name='language_rus',
        ),
        migrations.RemoveField(
            model_name='form',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='form',
            name='other_languages',
        ),
        migrations.RemoveField(
            model_name='form',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='form',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='form',
            name='profession',
        ),
        migrations.RemoveField(
            model_name='form',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='form',
            name='tiktok',
        ),
        migrations.RemoveField(
            model_name='form',
            name='video',
        ),
        migrations.RemoveField(
            model_name='form',
            name='weight',
        ),
        migrations.CreateModel(
            name='ApplicantToPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.form')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.position')),
            ],
        ),
    ]
