# Generated by Django 4.2.11 on 2024-05-29 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_form_about_me_remove_form_appearance_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicanttoposition',
            name='applicant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='api.form'),
        ),
        migrations.AlterField(
            model_name='applicanttoposition',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applicants', to='api.position'),
        ),
    ]
