# Generated by Django 4.2.11 on 2024-06-13 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_applicanttoposition_applicant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicanttoposition',
            name='applicant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='api.form'),
        ),
        migrations.AlterField(
            model_name='applicanttoposition',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applicants', to='api.position'),
        ),
    ]
